export const Data = {
  RegionNames: [
    {
      id: 1,
      name: "NCR",
    },
    {
      id: 2,
      name: "CALABARZON"
    }
  ],
  NCR: [
    {
      cityName: "Quezon City",
      barangayNames: [
        "Alicia",
        "Amihan",
        "Apolonio Samson",
        "Bagbag",
        "Bahay Toro",
        "Balingasa",
        "Batasan Hills",
        "Bayanihan",
        "Blue Ridge A",
        "Blue Ridge B",
        "Botocan",
        "Bungad",
        "Camp Aguinaldo",
        "Capri",
        "Central",
        "Claro",
        "Commonwealth",
        "Cubao",
        "Culiat",
        "Damar",
        "Damayan",
        "Del Monte",
        "Dioquino Zobel",
        "Don Manuel",
        "Doña Aurora",
        "Doña Imelda",
        "Doña Josefa",
        "Doña Petra",
        "Doña Vicenta",
        "East Kamias",
        "Escopa I",
        "Escopa II",
        "Fairview",
        "Gulod",
        "Horseshoe",
        "Immaculate Concepcion",
        "Kaligayahan",
        "Kalusugan",
        "Kamuning",
        "Katipunan",
        "Kaunlaran",
        "Krus na Ligas",
        "Laging Handa",
        "Libis",
        "Loyola Heights",
        "Lourdes",
        "Mangga",
        "Manresa",
        "Mariblo",
        "Masagana",
        "Masambong",
        "Matandang Balara",
        "Milagrosa",
        "Nagkaisang Nayon",
        "Nayong Kanluran",
        "New Era",
        "North Fairview",
        "Novaliches Proper",
        "Obra",
        "Old Capitol Site",
        "Olympia",
        "Paltok",
        "Paligsahan",
        "Paltok",
        "Pasong Putik",
        "Payatas",
        "Phil-Am",
        "Pinagkaisahan",
        "Pinagkaisahan",
        "Project 6",
        "Project 7",
        "Project 8",
        "Quirino 2-A",
        "Quirino 2-B",
        "Quirino 3-A",
        "Quirino 3-B",
        "Quirino 4-A",
        "Quirino 4-B",
        "Ramona",
        "Roxas",
        "Sacred Heart",
        "Saint Ignatius",
        "Saint Peter",
        "Salvacion",
        "San Agustin",
        "San Antonio",
        "San Bartolome",
        "San Isidro Labrador",
        "San Jose",
        "San Martin de Porres",
        "San Roque",
        "Santa Cruz",
        "Santa Lucia",
        "Santa Monica",
        "Santo Cristo",
        "Santo Domingo",
        "Santo Niño",
        "Sauyo",
        "Sienna",
        "Sikatuna Village",
        "Silangan",
        "Socorro",
        "South Triangle",
        "Tagumpay",
        "Talayan",
        "Tandang Sora",
        "Tatalon",
        "Teachers Village East",
        "Teachers Village West",
        "UP Campus",
        "UP Village",
        "Valencia",
        "Vasra",
        "Veterans Village",
        "Villa Maria Clara",
        "West Kamias",
        "West Triangle",
        "White Plains",
      ],
    },
    {
      cityName: "Manila",
      barangayNames: [
        "Barangay 1",
        "Barangay 2",
        "Barangay 3",
        "Barangay 4",
        "Barangay 5",
        "Barangay 6",
        "Barangay 7",
        "Barangay 8",
        "Barangay 9",
        "Barangay 10",
        "Barangay 11",
        "Barangay 12",
        "Barangay 13",
        "Barangay 14",
        "Barangay 15",
        "Barangay 16",
        "Barangay 17",
        "Barangay 18",
        "Barangay 19",
        "Barangay 20",
        "Barangay 21",
        "Barangay 22",
        "Barangay 23",
        "Barangay 24",
        "Barangay 25",
        "Barangay 26",
        "Barangay 27",
        "Barangay 28",
        "Barangay 29",
        "Barangay 30",
        "Barangay 31",
        "Barangay 32",
        "Barangay 33",
        "Barangay 34",
        "Barangay 35",
        "Barangay 36",
        "Barangay 37",
        "Barangay 38",
        "Barangay 39",
        "Barangay 40",
        "Barangay 41",
        "Barangay 42",
        "Barangay 43",
        "Barangay 44",
        "Barangay 45",
        "Barangay 46",
        "Barangay 47",
        "Barangay 48",
        "Barangay 49",
        "Barangay 50",
        "Barangay 51",
        "Barangay 52",
        "Barangay 53",
        "Barangay 54",
        "Barangay 55",
        "Barangay 56",
        "Barangay 57",
        "Barangay 58",
        "Barangay 59",
        "Barangay 60",
        "Barangay 61",
        "Barangay 62",
        "Barangay 63",
        "Barangay 64",
        "Barangay 65",
        "Barangay 66",
        "Barangay 67",
        "Barangay 68",
        "Barangay 69",
        "Barangay 70",
        "Barangay 71",
        "Barangay 72",
        "Barangay 73",
        "Barangay 74",
        "Barangay 75",
        "Barangay 76",
        "Barangay 77",
        "Barangay 78",
        "Barangay 79",
        "Barangay 80",
        "Barangay 81",
        "Barangay 82",
        "Barangay 83",
        "Barangay 84",
        "Barangay 85",
        "Barangay 86",
        "Barangay 87",
        "Barangay 88",
        "Barangay 89",
        "Barangay 90",
        "Barangay 91",
        "Barangay 92",
        "Barangay 93",
      ],
    },
    {
      cityName: "Caloocan",
      barangayNames: [
        "Bagbaguin",
        "Bagong Barrio East",
        "Bagong Barrio West",
        "Bagong Silang",
        "Bagumbong",
        "Camarin",
        "Caybiga",
        "Commonwealth",
        "Dampalit",
        "Deparo",
        "Grace Park East",
        "Grace Park West",
        "Heroes del 96",
        "Kaunlaran Village",
        "Llano",
        "Maypajo",
        "Moores",
        "Morning Breeze",
        "Novaliches Proper",
        "Pangarap Village",
        "Potrero",
        "San Agustin",
        "San Jose",
        "Santa Quiteria",
        "Tala",
        "Talipapa",
        "Unang Sigaw",
      ],
    },
    {
      cityName: "Las Piñas",
      barangayNames: [
        "Almanza Dos",
        "Almanza Uno",
        "B. F. International Village",
        "C. A. A. - B. F. International",
        "Daniel Fajardo",
        "Elias Aldana",
        "Ilaya",
        "Manuyo Dos",
        "Manuyo Uno",
        "Pamplona Dos",
        "Pamplona Tres",
        "Pamplona Uno",
        "Pilar Village",
        "Pulang Lupa Dos",
        "Pulang Lupa Uno",
        "Talon Dos",
        "Talon Kuatro",
        "Talon Singko",
        "Talon Tres",
        "Talon Uno",
      ],
    },
    {
      cityName: "Makati",
      barangayNames: [
        "Bangkal",
        "Bel-Air",
        "Carmona",
        "Cembo",
        "Comembo",
        "Dasmariñas",
        "East Rembo",
        "Forbes Park",
        "Guadalupe Nuevo",
        "Guadalupe Viejo",
        "Kasilawan",
        "La Paz",
        "Magallanes",
        "Olympia",
        "Palanan",
        "Pembo",
        "Pinagkaisahan",
        "Pio Del Pilar",
        "Poblacion",
        "Rizal",
        "San Antonio",
        "San Isidro",
        "San Lorenzo",
        "Santa Cruz",
        "Singkamas",
        "South Cembo",
        "Tejeros",
        "Urdaneta",
        "Valenzuela",
      ],
    },
    {
      cityName: "Malabon",
      barangayNames: [
        "Acacia",
        "Baritan",
        "Bayan-Bayanan",
        "Catmon",
        "Concepcion",
        "Dampalit",
        "Flores",
        "Hulong Duhat",
        "Ibaba",
        "Longos",
        "Maysilo",
        "Muzon",
        "Niugan",
        "Panghulo",
        "Potrero",
        "San Agustin",
        "Santolan",
        "Tañong",
        "Tinajeros",
        "Tonsuya",
        "Tugatog",
      ],
    },
    {
      cityName: "Mandaluyong",
      barangayNames: [
        "Barangka Drive",
        "Barangka Ibaba",
        "Barangka Ilaya",
        "Barangka Itaas",
        "Buayang Bato",
        "Hagdang Bato Itaas",
        "Hagdang Bato Libis",
        "Harapin Ang Bukas",
        "Highway Hills",
        "Hulo",
        "Mabini-J. Rizal",
        "Malamig",
        "Mauway",
        "New Zañiga",
        "Old Zañiga",
        "Pag-asa",
        "Plainview",
        "Pleasant Hills",
        "Poblacion",
        "San Jose",
        "Vergara",
        "Wack-Wack Greenhills",
      ],
    },
    {
      cityName: "Marikina",
      barangayNames: [
        "Barangka",
        "Calumpang",
        "Concepcion Dos",
        "Fortune",
        "Industrial Valley Complex",
        "Jesus Dela Peña",
        "Malanday",
        "Marikina Heights",
        "Nangka",
        "Parang",
        "San Roque",
        "Santa Elena",
        "Santo Niño",
        "Tañong",
        "Tumana",
      ],
    },
    {
      cityName: "Muntinlupa",
      barangayNames: [
        "Alabang",
        "Ayala Alabang",
        "Bayanan",
        "Buli",
        "Cupang",
        "Poblacion",
        "Putatan",
        "Sucat",
      ],
    },
    {
      cityName: "Navotas",
      barangayNames: [
        "Bagumbayan North",
        "Bagumbayan South",
        "Bangculasi",
        "Daanghari",
        "Navotas East",
        "Navotas West",
        "North Bay Boulevard North",
        "North Bay Boulevard South",
        "San Jose",
        "Sipac-Almacen",
        "Tangos North",
        "Tangos South",
      ],
    },
    {
      cityName: "Parañaque",
      barangayNames: [
        "Baclaran",
        "B. F. Homes",
        "Don Bosco",
        "Don Galo",
        "La Huerta",
        "Marcelo Green Village",
        "Merville",
        "Moonwalk",
        "San Antonio",
        "San Dionisio",
        "San Isidro",
        "San Martin de Porres",
        "Sun Valley",
        "Tambo",
        "Vitalez",
      ],
    },
    {
      cityName: "Pasay",
      barangayNames: [
        "Barangay 1",
        "Barangay 2",
        "Barangay 3",
        "Barangay 4",
        "Barangay 5",
        "Barangay 6",
        "Barangay 7",
        "Barangay 8",
        "Barangay 9",
        "Barangay 10",
        "Barangay 11",
        "Barangay 12",
        "Barangay 13",
        "Barangay 14",
        "Barangay 15",
        "Barangay 16",
        "Barangay 17",
        "Barangay 18",
        "Barangay 19",
        "Barangay 20",
        "Barangay 21",
        "Barangay 22",
        "Barangay 23",
        "Barangay 24",
        "Barangay 25",
        "Barangay 26",
        "Barangay 27",
        "Barangay 28",
        "Barangay 29",
        "Barangay 30",
        "Barangay 31",
        "Barangay 32",
        "Barangay 33",
        "Barangay 34",
        "Barangay 35",
        "Barangay 36",
        "Barangay 37",
        "Barangay 38",
        "Barangay 39",
        "Barangay 40",
        "Barangay 41",
        "Barangay 42",
        "Barangay 43",
        "Barangay 44",
        "Barangay 45",
      ],
    },
    {
      cityName: "Pasig",
      barangayNames: [
        "Bagong Ilog",
        "Bagong Katipunan",
        "Bambang",
        "Buting",
        "Caniogan",
        "Dela Paz",
        "Kalawaan",
        "Kapasigan",
        "Kapitolyo",
        "Malinao",
        "Manggahan",
        "Maybunga",
        "Oranbo",
        "Palatiw",
        "Pinagbuhatan",
        "Pineda",
        "Rosario",
        "Sagad",
        "San Antonio",
        "San Joaquin",
        "San Jose",
        "San Miguel",
        "San Nicolas",
        "Santa Cruz",
        "Santa Lucia",
        "Santa Rosa",
        "Santo Tomas",
        "Santolan",
        "Sumilang",
        "Ugong",
      ],
    },
    {
      cityName: "San Juan",
      barangayNames: [
        "Addition Hills",
        "Balong-Bato",
        "Batis",
        "Corazon de Jesus",
        "Ermitaño",
        "Greenhills",
        "Isabelita",
        "Kabayanan",
        "Little Baguio",
        "Maytunas",
        "Onse",
        "Pasadena",
        "Pedro Cruz",
        "Progreso",
        "Rivera",
        "Salapan",
        "San Perfecto",
        "Santa Lucia",
        "Tibagan",
        "West Crame",
      ],
    },
    {
      cityName: "Taguig",
      barangayNames: [
        "Bagumbayan",
        "Bambang",
        "Calzada",
        "Central Bicutan",
        "Central Signal Village",
        "Fort Bonifacio",
        "Hagonoy",
        "Ibayo-Tipas",
        "Katuparan",
        "Ligid-Tipas",
        "Lower Bicutan",
        "Maharlika Village",
        "Napindan",
        "New Lower Bicutan",
        "North Daang Hari",
        "North Signal Village",
        "Palingon",
        "Sampaloc",
        "San Miguel",
        "Santa Ana",
        "South Daang Hari",
        "South Signal Village",
        "Tanyag",
        "Tuktukan",
        "Upper Bicutan",
        "Ususan",
        "Wawa",
      ],
    },
    {
      cityName: "Valenzuela",
      barangayNames: [
        "Arkong Bato",
        "Bagbaguin",
        "Balangkas",
        "Bignay",
        "Bisig",
        "Canumay",
        "Coloong",
        "Dalandanan",
        "Gen. T. de Leon",
        "Isla",
        "Karuhatan",
        "Lawang Bato",
        "Lingunan",
        "Mabolo",
        "Malanday",
        "Malanding",
        "Mapulang Lupa",
        "Marulas",
        "Maysan",
        "Palasan",
        "Parada",
        "Pariancillo Villa",
        "Pasolo",
        "Poblacion",
        "Polo",
        "Punturin",
        "Rincon",
        "Tagalag",
        "Talasan",
        "Ugong",
        "Viente Reales",
      ],
    },
  ],
  CALABARZON: [
    {
      cityName: "Cavite City",
      barangayNames: [
        "Alapan I-A",
        "Alapan I-B",
        "Alapan II-A",
        "Alapan II-B",
        "Alapan II-C",
        "Alapan II-D",
        "Bahayang Pag-Asa",
        "H-2",
        "Kaingen",
        "Mabolo I",
        "Mabolo II",
        "Malainen Bago",
        "Malainen Luma I",
        "Malainen Luma II",
        "Poblacion I",
        "Poblacion II",
        "Poblacion III",
        "Poblacion IV",
        "Poblacion V",
        "San Antonio",
        "San Sebastian",
        "Santa Cruz I",
        "Santa Cruz II",
        "Santa Cruz III",
        "Santa Cruz IV",
        "Sineguelasan",
        "Tabing-Dagat",
      ],
    },
    {
      cityName: "San Pedro City",
      barangayNames: [
        "Nueva Victoria",
        "San Antonio",
        "San Roque",
        "San Lorenzo",
        "San Vicente",
        "Langgam",
        "Cuyab",
        "G.S.I.S.",
        "United Bayanihan",
        "San Pedro",
        "San Jose",
        "Fatima",
        "Candelaria",
        "Estrella",
        "Poblacion",
        "Napindan",
        "Landayan",
        "Santo Niño",
        "San Antonio (formerly Pook)",
        "San Isidro",
      ],
    },
    {
      cityName: "Santa Rosa City",
      barangayNames: [
        "Aplaya",
        "Balibago",
        "Caingin",
        "Dila",
        "Don Jose",
        "Macabling",
        "Malitlit",
        "Market Area",
        "Poblacion",
        "Sinalhan",
        "Tagapo",
        "Tartaria",
        "Ulat",
      ],
    },
    {
      cityName: "Biñan City",
      barangayNames: [
        "Barangay I (Poblacion)",
        "Barangay II (Poblacion)",
        "Barangay III (Poblacion)",
        "Barangay IV (Poblacion)",
        "Barangay V (Poblacion)",
        "Barangay VI (Poblacion)",
        "Barangay VII (Poblacion)",
        "Barangay VIII (Poblacion)",
        "Biñan (Hen. Francisco De Leon) (Poblacion)",
        "San Antonio (Poblacion)",
        "San Francisco (Poblacion)",
        "Santo Domingo (Poblacion)",
        "Turong",
        "Plaza",
        "PITX (formerly Gil Puyat)",
        "Canlalay",
        "Sta. Rosa-Tagaytay Road",
        "Mamplasan",
        "Santiago",
        "Loma",
        "Malaban",
        "San Vicente",
        "Timbao",
        "Dela Paz",
        "San Isidro",
      ],
    },
    {
      cityName: "Cabuyao City",
      barangayNames: [
        "Banlic",
        "Barandal",
        "Butong",
        "Casile",
        "Diezmo",
        "Gulod",
        "Halyo",
        "Hornalan",
        "Mamatid",
        "Maysilo",
        "Niugan",
        "Pulo",
        "Sampaguita Village",
        "San Isidro",
        "Tulo",
      ],
    },
    {
      cityName: "Calamba City",
      barangayNames: [
        "Bucal",
        "Barandal",
        "Ilaya",
        "Lecheria",
        "Majada Labas",
        "Majada In",
        "Market Subdivision",
        "Paciano Rizal",
        "Real",
        "Sampiruhan",
        "San Cristobal",
        "San Jose",
        "Turbina",
        "Ulango",
      ],
    },
    {
      cityName: "Los Baños",
      barangayNames: [
        "Anos",
        "Baybayin",
        "Bambang",
        "Maahas",
        "Malinta",
        "Mayondon",
        "Putho-Tuntungin",
        "San Antonio",
        "Tadlac",
        "Timugan",
        "Tuntungin-Putho",
      ],
    },
    {
      cityName: "San Pablo City",
      barangayNames: [
        "Barangay I-A (Pob.)",
        "Barangay I-B (Pob.)",
        "Barangay II-A (Pob.)",
        "Barangay II-B (Pob.)",
        "Barangay III-A (Pob.)",
        "Barangay III-B (Pob.)",
        "Barangay IV-A (Pob.)",
        "Barangay IV-B (Pob.)",
        "Barangay V-A (Pob.)",
        "Barangay V-B (Pob.)",
        "Barangay VI-A (Pob.)",
        "Barangay VI-B (Pob.)",
        "Barangay VII-A (Pob.)",
        "Barangay VII-B (Pob.)",
        "Barangay VIII-A (Pob.)",
        "Barangay VIII-B (Pob.)",
        "San Antonio",
        "Bagong Bayan",
        "Concepcion",
        "Dela Paz",
        "San Buenaventura",
        "San Francisco",
        "San Gabriel",
        "San Gregorio",
        "San Ildefonso",
        "San Isidro",
        "San Joaquin",
        "San Jose",
        "San Juan",
        "San Leonardo",
        "San Lorenzo",
        "San Lucas I",
        "San Lucas II",
        "San Marcos",
        "San Mateo",
        "San Miguel",
        "San Nicolas",
        "San Pedro",
        "San Rafael",
        "San Roque",
        "San Vicente",
        "Santo Angel Central",
        "Santo Angel Norte",
        "Santo Angel Sur",
        "Santo Cristo",
        "Santo Niño",
        "Soledad Norte",
        "Soledad Sur",
        "Tanghalan",
        "Catalina",
      ],
    },
    {
      cityName: "Lipa City",
      barangayNames: [
        "Anilao-Labac",
        "Antipolo del Norte",
        "Antipolo del Sur",
        "Bagong Pook",
        "Balintawak",
        "Barangay 1 (Pob.)",
        "Barangay 2 (Pob.)",
        "Barangay 3 (Pob.)",
        "Barangay 4 (Pob.)",
        "Barangay 5 (Pob.)",
        "Barangay 6 (Pob.)",
        "Barangay 7 (Pob.)",
        "Barangay 8 (Pob.)",
        "Barangay 9 (Pob.)",
        "Barangay 10 (Pob.)",
        "Barangay 11 (Pob.)",
        "Barangay 12 (Pob.)",
        "Bolbok",
        "Bugtong na Pulo",
        "Bulacnin",
        "Calamias",
        "Cumba",
        "Dagatan",
        "Duhatan",
        "Halang",
        "Inosluban",
        "Kayumanggi",
        "Latag",
        "Mabini",
        "Malagonlong",
        "Marauoy",
        "Nangkaan",
        "Pinagkawitan",
        "Saban",
        "San Benito",
        "San Carlos",
        "San Francisco",
        "San Guillermo",
        "San Jose",
        "San Juan",
        "San Lucas",
        "San Salvador",
        "Santo Niño (Bugtong na Pulo)",
        "Santo Niño (Pob.)",
        "Sapac",
        "Sico",
        "Tambo",
        "Tangob",
        "Tipacan",
        "Tubigan",
      ],
    },
    {
      cityName: "Batangas City",
      barangayNames: [
        "Alangilan",
        "Balagtas",
        "Banaba Center",
        "Banaba Kanluran",
        "Banaba Silangan",
        "Banaybanay",
        "Bilogo",
        "Cacawan",
        "Concepcion",
        "Conde Itaas",
        "Conde Labak",
        "Cuadra",
        "Del Pilar",
        "Gulod Labak",
        "Gulod Itaas",
        "Haligue Kanluran",
        "Haligue Silangan",
        "Ilijan",
        "Kumintang Ibaba",
        "Kumintang Ilaya",
        "Libjo",
        "Mahabang Dahilig",
        "Mahacot",
        "Malalim",
        "Malitam",
        "Marawoy",
        "Pallocan Kanluran",
        "Pallocan Silangan",
        "Pinamucan Proper",
        "Pinamucan Ibaba",
        "San Agustin",
        "San Andres",
        "San Antonio",
        "San Isidro",
        "San Jose Sico",
        "San Miguel",
        "San Pedro",
        "Santa Rita Aplaya",
        "Santa Rita Karsada",
        "Santo Domingo",
        "Santo Niño",
        "Sorosoro Ibaba",
        "Sorosoro Ilaya",
        "Sukol",
        "Talumpok Kanluran",
        "Talumpok Silangan",
        "Tingga Itaas",
        "Tingga Labak",
        "Tranca",
        "Wawa",
      ],
    },
    {
      cityName: "Tanauan City",
      barangayNames: [
        "Altura Bata",
        "Altura Matanda",
        "Bagumbayan",
        "Balele",
        "Banjo East",
        "Banjo Laurel",
        "Banjo Laurel (Malaking Pulo)",
        "Bilog-bilog",
        "Bolbok",
        "Bubuyan",
        "Bungad",
        "Butong",
        "Darasa",
        "Gonzales",
        "Hidalgo",
        "Janopol Occidental",
        "Janopol Oriental",
        "Luyos",
        "Mabini",
        "Malaking Pulo",
        "Maria Paz",
        "Montana",
        "Pagaspas",
        "Pantay Bata",
        "Pantay Matanda",
        "Poblacion Barangay 1",
        "Poblacion Barangay 2",
        "Poblacion Barangay 3",
        "Poblacion Barangay 4",
        "Poblacion Barangay 5",
        "Poblacion Barangay 6",
        "Poblacion Barangay 7",
        "Poblacion Barangay 8",
        "Poblacion Barangay 9",
        "Poblacion Barangay 10",
        "Poblacion Barangay 11",
        "Poblacion Barangay 12",
        "Poblacion Barangay 13",
        "Poblacion Barangay 14",
        "Poblacion Barangay 15",
        "Poblacion Barangay 16",
        "Poblacion Barangay 17",
        "Poblacion Barangay 18",
        "Poblacion Barangay 19",
        "Poblacion Barangay 20",
        "Sala",
        "Sambat",
        "Santor",
        "Sulpoc",
      ],
    },
    {
      cityName: "Sto. Tomas City",
      barangayNames: [
        "Balagbag",
        "Balele",
        "Bilucao",
        "Concepcion",
        "Lalakay",
        "Lodlod",
        "Lourdes",
        "Mabayabas",
        "Maharlika",
        "Maruclap",
        "Poblacion Barangay 1",
        "Poblacion Barangay 2",
        "Poblacion Barangay 3",
        "Poblacion Barangay 4",
        "Poblacion Barangay 5",
        "Poblacion Barangay 6",
        "Poblacion Barangay 7",
        "Poblacion Barangay 8",
        "Poblacion Barangay 9",
        "San Antonio",
        "San Bartolome",
        "San Felix",
        "San Isidro",
        "San Jose",
        "San Miguel",
        "San Pedro",
        "San Rafael",
        "San Roque",
        "San Vicente",
        "Santa Anastacia",
        "Santa Clara",
        "Santa Cruz",
        "Santa Elena",
        "Santa Maria",
        "Santo Niño",
        "Sinalhan",
      ],
    },
    {
      cityName: "Lucena City",
      barangayNames: [
        "Barangay 1 (Pob.)",
        "Barangay 2 (Pob.)",
        "Barangay 3 (Pob.)",
        "Barangay 4 (Pob.)",
        "Barangay 5 (Pob.)",
        "Barangay 6 (Pob.)",
        "Barangay 7 (Pob.)",
        "Barangay 8 (Pob.)",
        "Barangay 9 (Pob.)",
        "Barangay 10 (Pob.)",
        "Barangay 11 (Pob.)",
        "Barangay 12 (Pob.)",
        "Barangay 13 (Pob.)",
        "Barangay 14 (Pob.)",
        "Barangay 15 (Pob.)",
        "Barangay 16 (Pob.)",
        "Barangay 17 (Pob.)",
        "Barangay 18 (Pob.)",
        "Barangay 19 (Pob.)",
        "Barangay 20 (Pob.)",
        "Barangay 21 (Pob.)",
        "Barangay 22 (Pob.)",
        "Barangay 23 (Pob.)",
        "Barangay 24 (Pob.)",
        "Barangay 25 (Pob.)",
        "Barangay 26 (Pob.)",
        "Barangay 27 (Pob.)",
        "Barangay 28 (Pob.)",
        "Barangay 29 (Pob.)",
        "Barangay 30 (Pob.)",
        "Barangay 31 (Pob.)",
        "Barangay 32 (Pob.)",
        "Barangay 33 (Pob.)",
        "Barangay 34 (Pob.)",
        "Barangay 35 (Pob.)",
        "Barangay 36 (Pob.)",
        "Barangay 37 (Pob.)",
        "Barangay 38 (Pob.)",
        "Barangay 39 (Pob.)",
        "Barangay 40 (Pob.)",
        "Barangay 41 (Pob.)",
        "Barangay 42 (Pob.)",
        "Barangay 43 (Pob.)",
        "Barangay 44 (Pob.)",
        "Barangay 45 (Pob.)",
        "Barangay 46 (Pob.)",
        "Barangay 47 (Pob.)",
        "Barangay 48 (Pob.)",
        "Barangay 49 (Pob.)",
        "Barangay 50 (Pob.)",
      ],
    },
    {
      cityName: "Tayabas City",
      barangayNames: [
        "Aguilar",
        "Alitao",
        "Araw",
        "Atimonan Proper",
        "Avancena",
        "Baguio",
        "Balata",
        "Balubal",
        "Bantilan",
        "Buenavista",
        "Bukal",
        "Bunye South",
        "Calantas",
        "Camaysa",
        "Cambuga",
        "Canda",
        "Caniogan",
        "Cawayan I",
        "Cawayan II",
        "Dapdap",
        "Dominlog",
        "Evelyn",
        "Gibanga",
        "Gilayon",
        "Gumaca",
        "Ipilan",
        "Isabang",
        "Kalilayan",
        "Kalumpang",
        "Kamagong",
        "Kanlurang Malicboy",
        "Kanlurang Palale",
        "Kanlurang Poblacion",
        "Kanlurang San Diego",
        "Kanlurang Silangan",
        "Kanluran Bukal",
        "Kanluran Ibabang Iyam",
        "Kanluran Ibabang Talim",
        "Kanluran Ilaya",
        "Kanluran Ipilan",
        "Kanluran Malaoa",
        "Kanluran Malicboy",
        "Kanluran Malinao",
        "Kanluran Sampaloc",
        "Kanluran Santa Lucia",
        "Kanluran Tinamnan",
        "Kanluran Villegas",
        "Kipot",
        "Kulapi",
        "Lita",
        "Lukban I",
        "Lukban II",
        "Lukban III",
        "Lukban IV",
        "Lukban V",
        "Lukban VI",
        "Lukban VII",
        "Lukban VIII",
        "Lusacan",
        "Maunlad",
        "Mola Norte",
        "Mola Sur",
        "Montecillo",
        "Nangka Ibaba",
        "Nangka Ilaya",
        "Nangkaan",
        "Olla",
        "Osmeña",
        "Pakil",
        "Palale",
        "Palayan",
        "Patihan",
        "Pili",
        "Piis",
        "Pitogo",
        "Planada",
        "Poblacion I",
        "Poblacion II",
        "Poblacion III",
        "Poblacion IV",
        "Poblacion V",
        "Poblacion VI",
        "Poblacion VII",
        "Poblacion VIII",
        "Poblacion IX",
        "Poblacion X",
        "Poblacion XI",
        "Poblacion XII",
        "Poblacion XIII",
        "Poblacion XIV",
        "Poblacion XV",
        "Poblacion XVI",
        "Poblacion XVII",
        "Poblacion XVIII",
        "Poblacion XIX",
        "Poblacion XX",
        "Potol",
        "Prinza",
        "Pugon",
        "San Diego",
        "San Isidro Ibaba",
        "San Isidro Ilaya",
        "San Juan",
        "San Rafael Ibaba",
      ],
    },
    {
      cityName: "Candelaria",
      barangayNames: [
        "Abang",
        "Almacen",
        "Balagtasin",
        "Bukal Maligaya",
        "Calaocan",
        "Camangyanan",
        "Castañas",
        "Cawayanin Ibaba",
        "Cawayanin Ilaya",
        "Dayap",
        "Dolores",
        "Gatid",
        "Gibanga",
        "Inaclagan",
        "Inaon",
        "Kamagong",
        "Kanluran Bukal",
        "Kanluran Malabanban Norte",
        "Kanluran Malabanban Sur",
        "Kanluran Poblacion",
        "Kanluran San Jose",
        "Kanluran Santo Niño",
        "Kanluran Wakas",
        "Krus Na Ligas",
        "Lalig",
        "Libjo",
        "Lusacan",
        "Magsaysay",
        "Malabanban Norte",
        "Malabanban Sur",
        "Malusak",
        "Manggalang-Concepcion",
        "Masin",
        "Molinong I",
        "Molinong II",
        "Pahinga I",
        "Pahinga II",
        "Palayan",
        "Pinagbakuran",
        "Pinagkawitan",
        "Poblacion",
        "San Isidro Ibaba",
        "San Isidro Ilaya",
        "San Miguel",
        "San Roque",
        "Santa Catalina",
        "Santa Maria",
        "Silangang Bukal",
        "Silangang Malicboy",
        "Silangang Poblacion",
        "Silangang San Jose",
        "Silangang Santo Niño",
        "Silangang Wakas",
        "Sumilang",
        "Tamisian",
        "Tayabas Ibaba",
        "Tayabas Ilaya",
        "Tumbaga I",
        "Tumbaga II",
        "Ulbujan",
        "Villa Aurora",
        "Villa Mercedes",
        "Wakas",
      ],
    },
    {
      cityName: "Sariaya",
      barangayNames: [
        "Anos",
        "Banawang Daan",
        "Banawang Proper",
        "Bignay I",
        "Bignay II",
        "Bucal",
        "Bukal Maligaya",
        "Calantas",
        "Castillo",
        "Concepcion I",
        "Concepcion Banahaw",
        "Concepcion Palasan",
        "Concepcion Pinagbakuran",
        "Concepcion San Isidro",
        "Cotanda",
        "Dolores",
        "Gibanga",
        "Guiling",
        "Ipilan",
        "Lampos",
        "Lutucan Bata",
        "Lutucan Malabag",
        "Manggalang-Tulo",
        "Manggalang-Tubo",
        "Mansion",
        "Montecillo",
        "Morong",
        "Pili",
        "Poblacion I",
        "Poblacion II",
        "Poblacion III",
        "Poblacion IV",
        "Poblacion V",
        "San Antonio",
        "San Francisco",
        "San Isidro Labrador",
        "Talipan",
        "Tayuman",
        "Tumalim",
        "Villa Aurora",
        "Villa Magsino",
        "Wakas Norte",
        "Wakas Sur",
      ],
    },
    {
      cityName: "Lucban",
      barangayNames: [
        "Abang",
        "Aliliw",
        "Ayuti",
        "Barangay 1 (Pob.)",
        "Barangay 2 (Pob.)",
        "Barangay 3 (Pob.)",
        "Barangay 4 (Pob.)",
        "Barangay 5 (Pob.)",
        "Barangay 6 (Pob.)",
        "Barangay 7 (Pob.)",
        "Barangay 8 (Pob.)",
        "Barangay 9 (Pob.)",
        "Barangay 10 (Pob.)",
        "Barangay 11 (Pob.)",
        "Barangay 12 (Pob.)",
        "Barangay 13 (Pob.)",
        "Barangay 14 (Pob.)",
        "Barangay 15 (Pob.)",
        "Barangay 16 (Pob.)",
        "Barangay 17 (Pob.)",
        "Barangay 18 (Pob.)",
        "Barangay 19 (Pob.)",
        "Barangay 20 (Pob.)",
        "Barangay 21 (Pob.)",
        "Barangay 22 (Pob.)",
        "Barangay 23 (Pob.)",
        "Barangay 24 (Pob.)",
        "Barangay 25 (Pob.)",
        "Barangay 26 (Pob.)",
        "Barangay 27 (Pob.)",
        "Barangay 28 (Pob.)",
        "Barangay 29 (Pob.)",
        "Barangay 30 (Pob.)",
        "Barangay 31 (Pob.)",
        "Barangay 32 (Pob.)",
        "Barangay 33 (Pob.)",
        "Barangay 34 (Pob.)",
        "Barangay 35 (Pob.)",
        "Barangay 36 (Pob.)",
        "Barangay 37 (Pob.)",
        "Barangay 38 (Pob.)",
        "Barangay 39 (Pob.)",
        "Barangay 40 (Pob.)",
        "Barangay 41 (Pob.)",
        "Barangay 42 (Pob.)",
        "Barangay 43 (Pob.)",
        "Barangay 44 (Pob.)",
        "Barangay 45 (Pob.)",
        "Barangay 46 (Pob.)",
        "Barangay 47 (Pob.)",
        "Barangay 48 (Pob.)",
        "Barangay 49 (Pob.)",
        "Barangay 50 (Pob.)",
      ],
    },
    {
      cityName: "Mauban",
      barangayNames: [
        "Alitao",
        "Amuguis",
        "Atimonan",
        "Bagong Silang",
        "Balaybalay",
        "Banahaw",
        "Bantigue",
        "Cambuga",
        "Camoning",
        "Candangal",
        "Capanaligan",
        "Cawayanin Ibaba",
        "Cawayanin Ilaya",
        "Cogorin",
        "Dayap",
        "Ilayang Mandaon",
        "Ilayang Palsabangon",
        "Kamias",
        "Kamputong",
        "Kanluran Malabanban Norte",
        "Kanluran Malabanban Sur",
        "Lual",
        "Lumutan",
        "Lusacan",
        "Lutucan Malabag",
        "Lutucan Bata",
        "Magdalo",
        "Malabanban Norte",
        "Malabanban Sur",
        "Maliwag",
        "Manguiring",
        "Mukal",
        "Palsabangon",
        "Patihan",
        "Pinagbayanan",
        "Poblacion I",
        "Poblacion II",
        "Sampaloc",
        "Siclong Ibaba",
        "Siclong Ilaya",
        "Sicsican",
        "Sugod",
        "Tabing Ilog",
        "Talaba",
        "Talolong",
        "Tamlong",
        "Tiniguiban",
        "Villaarcaya",
      ],
    },
    {
      cityName: "Tagaytay City",
      barangayNames: [
        "Asisan",
        "Bagong Tubig",
        "Calabuso",
        "Dapdap West",
        "Dapdap East",
        "Francisco",
        "Guinhawa South",
        "Guinhawa North",
        "Iruhin East",
        "Iruhin South",
        "Iruhin West",
        "Kaybagal North",
        "Kaybagal South (Poblacion)",
        "Mag-asawang Ilat",
        "Maharlika East",
        "Maharlika West",
        "Maitim 2nd Central",
        "Maitim 2nd East",
        "Maitim 2nd West",
        "Mendez Crossing East",
        "Mendez Crossing West",
        "Neogan",
        "Patutong Malaki North",
        "Patutong Malaki South",
        "Sambong",
        "San Jose",
        "San Miguel",
        "Silang Junction North",
        "Silang Junction South",
        "Sungay East",
        "Sungay West",
        "Tolentino East",
        "Tolentino West",
      ],
    },
    {
      cityName: "Gumaca",
      barangayNames: [
        "Aloneros",
        "Anonangin",
        "Bacungan",
        "Baguio",
        "Balanacan",
        "Balubad",
        "Barangay 1 (Pob.)",
        "Barangay 2 (Pob.)",
        "Barangay 3 (Pob.)",
        "Barangay 4 (Pob.)",
        "Barangay 5 (Pob.)",
        "Barangay 6 (Pob.)",
        "Barangay 7 (Pob.)",
        "Barangay 8 (Pob.)",
        "Barangay 9 (Pob.)",
        "Barangay 10 (Pob.)",
        "Barangay 11 (Pob.)",
        "Barangay 12 (Pob.)",
        "Barangay 13 (Pob.)",
        "Barangay 14 (Pob.)",
        "Barangay 15 (Pob.)",
        "Barangay 16 (Pob.)",
        "Barangay 17 (Pob.)",
        "Barangay 18 (Pob.)",
        "Barangay 19 (Pob.)",
        "Barangay 20 (Pob.)",
        "Barangay 21 (Pob.)",
        "Barangay 22 (Pob.)",
        "Barangay 23 (Pob.)",
        "Barangay 24 (Pob.)",
        "Barangay 25 (Pob.)",
        "Barangay 26 (Pob.)",
        "Barangay 27 (Pob.)",
        "Barangay 28 (Pob.)",
        "Barangay 29 (Pob.)",
        "Barangay 30 (Pob.)",
        "Barangay 31 (Pob.)",
        "Barangay 32 (Pob.)",
        "Barangay 33 (Pob.)",
        "Barangay 34 (Pob.)",
        "Barangay 35 (Pob.)",
        "Barangay 36 (Pob.)",
        "Barangay 37 (Pob.)",
        "Barangay 38 (Pob.)",
        "Barangay 39 (Pob.)",
        "Barangay 40 (Pob.)",
        "Barangay 41 (Pob.)",
        "Barangay 42 (Pob.)",
        "Barangay 43 (Pob.)",
        "Barangay 44 (Pob.)",
        "Barangay 45 (Pob.)",
      ],
    },
    {
      cityName: "Pagbilao",
      barangayNames: [
        "Alupaye",
        "Anonangin",
        "Bukal Maligaya",
        "Bukalasa",
        "Bulakin I",
        "Bulakin II",
        "Ibabang Bagumbungan",
        "Ibabang Palsabangon",
        "Ibabang Polo",
        "Ibabang Sapa",
        "Ibabang Taykin",
        "Ilayang Bagumbungan",
        "Ilayang Palsabangon",
        "Ilayang Polo",
        "Ilayang Sapa",
        "Ilayang Taykin",
        "Inaclagan",
        "Kanlurang Maligaya",
        "Kanlurang Paki",
        "Kanlurang Palsabangon",
        "Kanlurang Polo",
        "Kanlurang Sapa",
        "Kanlurang Taykin",
        "Kulapi",
        "Lopez Jaena",
        "Magsaysay",
        "Mapagong",
        "Matangtubig",
        "Osmeña",
        "Poblacion I",
        "Poblacion II",
        "Poblacion III",
        "Poblacion IV",
        "Poblacion V",
        "Poblacion VI",
        "San Antonio",
        "San Diego",
        "San Francisco",
        "San Isidro",
        "San Jose",
        "San Juan",
        "San Pedro I",
        "San Pedro II",
        "San Roque",
        "Sariaya",
        "Sariaya Road",
        "Villa Arcaya",
        "Villa Barra",
        "Villa Espina",
        "Villa Felomina",
        "Villa Nava",
        "Villa Novaliches",
        "Villa Paitan",
        "Villa Reyes",
        "Villa San Agustin",
        "Villa San Carlos",
        "Villa San Diego",
        "Villa San Francisco",
        "Villa San Gregorio",
        "Villa San Isidro",
        "Villa San Jose",
        "Villa San Juan",
        "Villa San Pedro",
        "Villa San Roque",
        "Villa San Vicente",
        "Villa Santiago",
        "Villa Victoria",
      ],
    },
    {
      cityName: "Tiaong",
      barangayNames: [
        "Alon",
        "Ayusan I",
        "Ayusan II",
        "Ayusan III",
        "Bagong Bahay",
        "Bantigue",
        "Barangay Zone I (Pob.)",
        "Barangay Zone II (Pob.)",
        "Barangay Zone III (Pob.)",
        "Barangay Zone IV (Pob.)",
        "Barangay Zone V (Pob.)",
        "Barangay Zone VI (Pob.)",
        "Barangay Zone VII (Pob.)",
        "Calumpang",
        "Campo",
        "Cawayan",
        "Dayap",
        "Ipilan",
        "Isla",
        "Kanlurang Bukal",
        "Kanlurang Maligaya",
        "Kanluran Bukid",
        "Kanluran Malaki",
        "Lalig",
        "Latag",
        "Lusacan",
        "Manggahan",
        "Masalukot I",
        "Masalukot II",
        "May-it",
        "Pilahan",
        "Sambat",
        "San Francisco",
        "San Isidro",
        "San Jose",
        "San Juan",
        "San Miguel",
        "San Roque",
        "Santa Catalina",
        "Santa Cruz",
        "Santa Lucia",
        "Santa Maria",
        "Santa Rita",
        "Silangang Bukid",
        "Silangang Maligaya",
        "Silangan Bukal",
        "Silangan Malaki",
        "Villa Ibaba",
        "Villa Ilaya",
        "Villa Principe",
        "Villa Victoria",
      ],
    },
    {
      cityName: "San Antonio",
      barangayNames: [
        "Anoling",
        "Bagong Pook",
        "Banaba",
        "Banilad",
        "Buhanginan",
        "Bulakin I",
        "Bulakin II",
        "Calumpang",
        "Candelaria",
        "Concepcion",
        "Dalipit East",
        "Dalipit West",
        "Dayap",
        "Inosloban",
        "Lalig",
        "Lapidario",
        "Manggahan",
        "Masalukot I",
        "Masalukot II",
        "Masalukot III",
        "Munting Indang",
        "Palaypalay",
        "Pinagbayanan",
        "Sambat",
        "San Agustin",
        "San Isidro",
        "San Jose",
        "San Juan",
        "San Roque",
        "Santa Barbara",
        "Santa Catalina",
        "Santa Cruz",
        "Santa Lucia",
        "Santa Maria",
        "Santa Teresita",
        "Santo Niño",
      ],
    },
    {
      cityName: "Catanauan",
      barangayNames: [
        "Balubad",
        "Bamban",
        "Bato",
        "Calimpak",
        "Camandiison",
        "Cawayan",
        "Culilang",
        "Dumacaa",
        "Lubigan",
        "Mabini",
        "Macasin",
        "Mahabang Lalim",
        "Malabahay",
        "Malaking Ambling",
        "Malaking Ilog",
        "Malapad",
        "Maliwanag",
        "Manggalang",
        "Manguisian",
        "Matandang Sabang",
        "Maybancal",
        "Palindan Ibaba",
        "Palindan Ilaya",
        "Pinagbayanan",
        "Pinagdanlayan",
        "Poblacion I",
        "Poblacion II",
        "Poblacion III",
        "Poblacion IV",
        "Poblacion V",
        "San Antonio",
        "Santo Cristo",
        "Sisimbulan",
        "Subol",
        "Talabaan",
        "Tibag",
        "Tipaz",
        "Villa Aurora",
      ],
    },
    {
      cityName: "Atimonan",
      barangayNames: [
        "Alibijaban",
        "Alugan",
        "Apitong",
        "Bakia",
        "Balubad",
        "Bantigue",
        "Buensuceso",
        "Buhangin",
        "Bukal Sur",
        "Bukal Norte",
        "Cabulihan",
        "Calantas",
        "Cawayanin Ibaba",
        "Cawayanin Ilaya",
        "Concepcion",
        "Dapdap",
        "Don Tomas",
        "Gango",
        "Habingan",
        "Hinguiwin",
        "Ipilan",
        "Lubigan",
        "Magsaysay",
        "Malinao",
        "Maputat",
        "Matanag",
        "Matucad",
        "Mazahan",
        "Pacabit",
        "Pagutlan",
        "Palale",
        "Perez",
        "Plaridel",
        "Poblacion 1",
        "Poblacion 2",
        "Poblacion 3",
        "Poblacion 4",
        "Poblacion 5",
        "Poblacion 6",
        "Poblacion 7",
        "Poblacion 8",
        "Poblacion 9",
        "Poblacion 10",
        "Poblacion 11",
        "Poblacion 12",
        "Poblacion 13",
        "Poblacion 14",
        "Poblacion 15",
        "Poblacion 16",
        "Poblacion 17",
        "Poblacion 18",
        "Poblacion 19",
        "Poblacion 20",
        "Poblacion 21",
        "Poblacion 22",
        "Poblacion 23",
        "Poblacion 24",
        "Poblacion 25",
        "Poblacion 26",
        "Poblacion 27",
        "Poblacion 28",
        "Poblacion 29",
        "Poblacion 30",
        "Poblacion 31",
      ],
    },
    {
      cityName: "Padre Burgos",
      barangayNames: [
        "Barangay 1 (Pob.)",
        "Barangay 2 (Pob.)",
        "Barangay 3 (Pob.)",
        "Barangay 4 (Pob.)",
        "Barangay 5 (Pob.)",
        "Barangay 6 (Pob.)",
        "Barangay 7 (Pob.)",
        "Barangay 8 (Pob.)",
        "Barangay 9 (Pob.)",
        "Barangay 10 (Pob.)",
        "Barangay 11 (Pob.)",
        "Barangay 12 (Pob.)",
        "Barangay 13 (Pob.)",
        "Barangay 14 (Pob.)",
        "Barangay 15 (Pob.)",
        "Barangay 16 (Pob.)",
        "Barangay 17 (Pob.)",
        "Barangay 18 (Pob.)",
        "Barangay 19 (Pob.)",
        "Barangay 20 (Pob.)",
        "Barangay 21 (Pob.)",
        "Barangay 22 (Pob.)",
        "Barangay 23 (Pob.)",
        "Barangay 24 (Pob.)",
        "Barangay 25 (Pob.)",
        "Barangay 26 (Pob.)",
        "Barangay 27 (Pob.)",
        "Barangay 28 (Pob.)",
        "Barangay 29 (Pob.)",
        "Barangay 30 (Pob.)",
        "Barangay 31 (Pob.)",
        "Barangay 32 (Pob.)",
        "Barangay 33 (Pob.)",
        "Barangay 34 (Pob.)",
        "Barangay 35 (Pob.)",
        "Barangay 36 (Pob.)",
        "Barangay 37 (Pob.)",
        "Barangay 38 (Pob.)",
        "Barangay 39 (Pob.)",
        "Barangay 40 (Pob.)",
        "Barangay 41 (Pob.)",
        "Barangay 42 (Pob.)",
        "Barangay 43 (Pob.)",
        "Barangay 44 (Pob.)",
        "Barangay 45 (Pob.)",
        "Barangay 46 (Pob.)",
        "Barangay 47 (Pob.)",
        "Barangay 48 (Pob.)",
        "Barangay 49 (Pob.)",
        "Barangay 50 (Pob.)",
      ],
    },
    {
      cityName: "Unisan",
      barangayNames: [
        "Anonangin",
        "Bagong Bayan",
        "Banguingui",
        "Buenavista",
        "Calimpak",
        "Capamana",
        "Catayungan",
        "Concepcion",
        "Corazon",
        "Dawis",
        "Hilantagaan",
        "Imelda",
        "Ipilan",
        "La Medalla",
        "Lourdes",
        "Mabini",
        "Magdalena",
        "Mahayhay",
        "Malbago",
        "Maligaya",
        "Nabuslot",
        "Nalunao",
        "Natividad",
        "Pamilihan",
        "Poblacion",
        "Ponon",
        "Sampaloc",
        "San Andres",
        "San Antonio",
        "San Francisco",
        "San Isidro",
        "San Jose",
        "San Nicolas",
        "San Roque",
        "Santa Catalina",
        "Santa Cruz",
        "Santa Elena",
        "Santa Monica",
        "Santo Domingo",
        "Santo Niño",
        "Sugcad",
        "Talabaan",
        "Tamulay",
        "Tan-ag",
        "Tubigan",
      ],
    },
    {
      cityName: "Agdangan",
      barangayNames: [
        "Anahawan",
        "Bantigue",
        "Bulagsong",
        "Kilait",
        "Labnig",
        "Lacdayan",
        "Poblacion",
        "Sampaguita",
        "San Isidro",
      ],
    },
    {
      cityName: "Pitogo",
      barangayNames: [
        "Alibihaban",
        "Anibongan",
        "Balatasan",
        "Banog",
        "Bayanihan (Pob.)",
        "Binuangan",
        "Bobongan",
        "Bonifacio (Pob.)",
        "Bulagsong",
        "Cagbalete",
        "Calantas",
        "Cawayanin Ibaba",
        "Cawayanin Ilaya",
        "Dapdap",
        "Gahonon",
        "Halawig",
        "Ipil",
        "Katipunan (Pob.)",
        "Kilait",
        "Lahing",
        "Landing",
        "Lantik",
        "Lopez Jaena (Pob.)",
        "Mabini (Pob.)",
        "Maunlad (Pob.)",
        "Nakalaya",
        "Pandanan",
        "Quezon (Pob.)",
        "Rizal (Pob.)",
        "San Isidro",
        "San Jose",
        "San Roque",
        "Santa Cruz (Pob.)",
        "Silanganan",
        "Tres Reyes (Pob.)",
        "Villa Mercedes",
        "Villa Patria",
      ],
    },
    {
      cityName: "Gumaca",
      barangayNames: [
        "Bagong Pag-Asa",
        "Binambang",
        "Del Carmen",
        "Lalig",
        "Lupac",
        "Mabini",
        "Malaya",
        "Monteclaro",
        "Poblacion 1",
        "Poblacion 2",
        "San Isidro",
        "San Jose",
        "San Juan",
        "San Roque",
        "Santa Cruz",
        "Villa Arcaya",
        "Villa Mendoza",
      ],
    },
    {
      cityName: "Macalelon",
      barangayNames: [
        "Almacen",
        "Alupay",
        "Bacungan",
        "Badiangan",
        "Bantad",
        "Batabat Norte",
        "Batabat Sur",
        "Buenavista",
        "Bulusan",
        "Calantas",
        "Canluran",
        "Cawayan",
        "Cawayanan",
        "Cawayang Bugtong",
        "Del Pilar",
        "Dumadalig",
        "Gamay",
        "Gata",
        "Guinhalinan",
        "Ilayang Bayucain",
        "Ilayang Cawayan",
        "Ilayang Dupay",
        "Ilayang Ipil",
        "Ilayang Silonay",
        "Ilayang Yuni",
        "Inaclagan",
        "Lamit",
        "Magsikap",
        "Marupit",
        "Masalukot Ilaya",
        "Masalukot Kanluran",
        "Pagkakaisa",
        "Pandanan",
        "Pangpang",
        "Payapa Ibaba",
        "Payapa Ilaya",
        "Poblacion Ilaya",
        "Poblacion Ibaba",
        "Quirino",
        "San Isidro",
        "San Rafael",
        "Santa Brigida",
        "Santa Cruz",
        "Taguin",
        "Taytay",
        "Villa Belen",
      ],
    },
    {
      cityName: "General Nakar",
      barangayNames: [
        "Poblacion",
        "Calutcot",
        "Magsaysay",
        "San Marcelino",
        "Umiray",
        "Wawa",
      ],
    },
    {
      cityName: "Real",
      barangayNames: [
        "Bagumbayan",
        "Balagbag",
        "Barangay I (Poblacion)",
        "Barangay II (Poblacion)",
        "Barangay III (Poblacion)",
        "Barangay IV (Poblacion)",
        "Caniwan",
        "Kiloloron",
        "Llavac",
        "Maragondon",
        "Nakar",
        "Pagkakaisa",
        "Tignoan",
      ],
    },
    {
      cityName: "Infanta",
      barangayNames: [
        "Poblacion",
        "Calasag",
        "Barangay 1 (San Juan)",
        "Barangay 2 (San Francisco)",
        "Barangay 3 (San Isidro)",
        "Barangay 4 (San Roque)",
        "Barangay 5 (San Antonio)",
        "Barangay 6 (Santa Catalina)",
        "Barangay 7 (Santa Monica)",
        "Barangay 8 (San Jose)",
        "Barangay 9 (San Miguel)",
        "Barangay 10 (San Andres)",
        "Barangay 11 (San Pedro)",
        "Barangay 12 (Santa Maria)",
        "Barangay 13 (Santo Domingo)",
        "Barangay 14 (San Agustin)",
        "Barangay 15 (San Nicolas)",
        "Barangay 16 (San Jose)",
        "Barangay 17 (San Antonio)",
        "Barangay 18 (San Francisco)",
        "Barangay 19 (San Juan)",
      ],
    },
  ],
};
