export const Data = {
  cities: [
    {
      cityName: "Quezon City",
      barangayNames: [
        "Alicia",
        "Amihan",
        "Apolonio Samson",
        "Bagbag",
        "Bahay Toro",
        "Balingasa",
        "Batasan Hills",
        "Bayanihan",
        "Blue Ridge A",
        "Blue Ridge B",
        "Botocan",
        "Bungad",
        "Camp Aguinaldo",
        "Capri",
        "Central",
        "Claro",
        "Commonwealth",
        "Cubao",
        "Culiat",
        "Damar",
        "Damayan",
        "Del Monte",
        "Dioquino Zobel",
        "Don Manuel",
        "Doña Aurora",
        "Doña Imelda",
        "Doña Josefa",
        "Doña Petra",
        "Doña Vicenta",
        "East Kamias",
        "Escopa I",
        "Escopa II",
        "Fairview",
        "Gulod",
        "Horseshoe",
        "Immaculate Concepcion",
        "Kaligayahan",
        "Kalusugan",
        "Kamuning",
        "Katipunan",
        "Kaunlaran",
        "Krus na Ligas",
        "Laging Handa",
        "Libis",
        "Loyola Heights",
        "Lourdes",
        "Mangga",
        "Manresa",
        "Mariblo",
        "Masagana",
        "Masambong",
        "Matandang Balara",
        "Milagrosa",
        "Nagkaisang Nayon",
        "Nayong Kanluran",
        "New Era",
        "North Fairview",
        "Novaliches Proper",
        "Obra",
        "Old Capitol Site",
        "Olympia",
        "Paltok",
        "Paligsahan",
        "Paltok",
        "Pasong Putik",
        "Payatas",
        "Phil-Am",
        "Pinagkaisahan",
        "Pinagkaisahan",
        "Project 6",
        "Project 7",
        "Project 8",
        "Quirino 2-A",
        "Quirino 2-B",
        "Quirino 3-A",
        "Quirino 3-B",
        "Quirino 4-A",
        "Quirino 4-B",
        "Ramona",
        "Roxas",
        "Sacred Heart",
        "Saint Ignatius",
        "Saint Peter",
        "Salvacion",
        "San Agustin",
        "San Antonio",
        "San Bartolome",
        "San Isidro Labrador",
        "San Jose",
        "San Martin de Porres",
        "San Roque",
        "Santa Cruz",
        "Santa Lucia",
        "Santa Monica",
        "Santo Cristo",
        "Santo Domingo",
        "Santo Niño",
        "Sauyo",
        "Sienna",
        "Sikatuna Village",
        "Silangan",
        "Socorro",
        "South Triangle",
        "Tagumpay",
        "Talayan",
        "Tandang Sora",
        "Tatalon",
        "Teachers Village East",
        "Teachers Village West",
        "UP Campus",
        "UP Village",
        "Valencia",
        "Vasra",
        "Veterans Village",
        "Villa Maria Clara",
        "West Kamias",
        "West Triangle",
        "White Plains",
      ],
    },
    {
      cityName: "Manila",
      barangayNames: [
        "Barangay 1",
        "Barangay 2",
        "Barangay 3",
        "Barangay 4",
        "Barangay 5",
        "Barangay 6",
        "Barangay 7",
        "Barangay 8",
        "Barangay 9",
        "Barangay 10",
        "Barangay 11",
        "Barangay 12",
        "Barangay 13",
        "Barangay 14",
        "Barangay 15",
        "Barangay 16",
        "Barangay 17",
        "Barangay 18",
        "Barangay 19",
        "Barangay 20",
        "Barangay 21",
        "Barangay 22",
        "Barangay 23",
        "Barangay 24",
        "Barangay 25",
        "Barangay 26",
        "Barangay 27",
        "Barangay 28",
        "Barangay 29",
        "Barangay 30",
        "Barangay 31",
        "Barangay 32",
        "Barangay 33",
        "Barangay 34",
        "Barangay 35",
        "Barangay 36",
        "Barangay 37",
        "Barangay 38",
        "Barangay 39",
        "Barangay 40",
        "Barangay 41",
        "Barangay 42",
        "Barangay 43",
        "Barangay 44",
        "Barangay 45",
        "Barangay 46",
        "Barangay 47",
        "Barangay 48",
        "Barangay 49",
        "Barangay 50",
        "Barangay 51",
        "Barangay 52",
        "Barangay 53",
        "Barangay 54",
        "Barangay 55",
        "Barangay 56",
        "Barangay 57",
        "Barangay 58",
        "Barangay 59",
        "Barangay 60",
        "Barangay 61",
        "Barangay 62",
        "Barangay 63",
        "Barangay 64",
        "Barangay 65",
        "Barangay 66",
        "Barangay 67",
        "Barangay 68",
        "Barangay 69",
        "Barangay 70",
        "Barangay 71",
        "Barangay 72",
        "Barangay 73",
        "Barangay 74",
        "Barangay 75",
        "Barangay 76",
        "Barangay 77",
        "Barangay 78",
        "Barangay 79",
        "Barangay 80",
        "Barangay 81",
        "Barangay 82",
        "Barangay 83",
        "Barangay 84",
        "Barangay 85",
        "Barangay 86",
        "Barangay 87",
        "Barangay 88",
        "Barangay 89",
        "Barangay 90",
        "Barangay 91",
        "Barangay 92",
        "Barangay 93",
      ],
    },
    {
      cityName: "Caloocan",
      barangayNames: [
        "Bagbaguin",
        "Bagong Barrio East",
        "Bagong Barrio West",
        "Bagong Silang",
        "Bagumbong",
        "Camarin",
        "Caybiga",
        "Commonwealth",
        "Dampalit",
        "Deparo",
        "Grace Park East",
        "Grace Park West",
        "Heroes del 96",
        "Kaunlaran Village",
        "Llano",
        "Maypajo",
        "Moores",
        "Morning Breeze",
        "Novaliches Proper",
        "Pangarap Village",
        "Potrero",
        "San Agustin",
        "San Jose",
        "Santa Quiteria",
        "Tala",
        "Talipapa",
        "Unang Sigaw",
      ],
    },
    {
      cityName: "Las Piñas",
      barangayNames: [
        "Almanza Dos",
        "Almanza Uno",
        "B. F. International Village",
        "C. A. A. - B. F. International",
        "Daniel Fajardo",
        "Elias Aldana",
        "Ilaya",
        "Manuyo Dos",
        "Manuyo Uno",
        "Pamplona Dos",
        "Pamplona Tres",
        "Pamplona Uno",
        "Pilar Village",
        "Pulang Lupa Dos",
        "Pulang Lupa Uno",
        "Talon Dos",
        "Talon Kuatro",
        "Talon Singko",
        "Talon Tres",
        "Talon Uno",
      ],
    },
    {
      cityName: "Makati",
      barangayNames: [
        "Bangkal",
        "Bel-Air",
        "Carmona",
        "Cembo",
        "Comembo",
        "Dasmariñas",
        "East Rembo",
        "Forbes Park",
        "Guadalupe Nuevo",
        "Guadalupe Viejo",
        "Kasilawan",
        "La Paz",
        "Magallanes",
        "Olympia",
        "Palanan",
        "Pembo",
        "Pinagkaisahan",
        "Pio Del Pilar",
        "Poblacion",
        "Rizal",
        "San Antonio",
        "San Isidro",
        "San Lorenzo",
        "Santa Cruz",
        "Singkamas",
        "South Cembo",
        "Tejeros",
        "Urdaneta",
        "Valenzuela",
      ],
    },
    {
      cityName: "Malabon",
      barangayNames: [
        "Acacia",
        "Baritan",
        "Bayan-Bayanan",
        "Catmon",
        "Concepcion",
        "Dampalit",
        "Flores",
        "Hulong Duhat",
        "Ibaba",
        "Longos",
        "Maysilo",
        "Muzon",
        "Niugan",
        "Panghulo",
        "Potrero",
        "San Agustin",
        "Santolan",
        "Tañong",
        "Tinajeros",
        "Tonsuya",
        "Tugatog",
      ],
    },
    {
      cityName: "Mandaluyong",
      barangayNames: [
        "Barangka Drive",
        "Barangka Ibaba",
        "Barangka Ilaya",
        "Barangka Itaas",
        "Buayang Bato",
        "Hagdang Bato Itaas",
        "Hagdang Bato Libis",
        "Harapin Ang Bukas",
        "Highway Hills",
        "Hulo",
        "Mabini-J. Rizal",
        "Malamig",
        "Mauway",
        "New Zañiga",
        "Old Zañiga",
        "Pag-asa",
        "Plainview",
        "Pleasant Hills",
        "Poblacion",
        "San Jose",
        "Vergara",
        "Wack-Wack Greenhills",
      ],
    },
    {
      cityName: "Marikina",
      barangayNames: [
        "Barangka",
        "Calumpang",
        "Concepcion Dos",
        "Fortune",
        "Industrial Valley Complex",
        "Jesus Dela Peña",
        "Malanday",
        "Marikina Heights",
        "Nangka",
        "Parang",
        "San Roque",
        "Santa Elena",
        "Santo Niño",
        "Tañong",
        "Tumana",
      ],
    },
    {
      cityName: "Muntinlupa",
      barangayNames: [
        "Alabang",
        "Ayala Alabang",
        "Bayanan",
        "Buli",
        "Cupang",
        "Poblacion",
        "Putatan",
        "Sucat",
      ],
    },
    {
      cityName: "Navotas",
      barangayNames: [
        "Bagumbayan North",
        "Bagumbayan South",
        "Bangculasi",
        "Daanghari",
        "Navotas East",
        "Navotas West",
        "North Bay Boulevard North",
        "North Bay Boulevard South",
        "San Jose",
        "Sipac-Almacen",
        "Tangos North",
        "Tangos South",
      ],
    },
    {
      cityName: "Parañaque",
      barangayNames: [
        "Baclaran",
        "B. F. Homes",
        "Don Bosco",
        "Don Galo",
        "La Huerta",
        "Marcelo Green Village",
        "Merville",
        "Moonwalk",
        "San Antonio",
        "San Dionisio",
        "San Isidro",
        "San Martin de Porres",
        "Sun Valley",
        "Tambo",
        "Vitalez",
      ],
    },
    {
      cityName: "Pasay",
      barangayNames: [
        "Barangay 1",
        "Barangay 2",
        "Barangay 3",
        "Barangay 4",
        "Barangay 5",
        "Barangay 6",
        "Barangay 7",
        "Barangay 8",
        "Barangay 9",
        "Barangay 10",
        "Barangay 11",
        "Barangay 12",
        "Barangay 13",
        "Barangay 14",
        "Barangay 15",
        "Barangay 16",
        "Barangay 17",
        "Barangay 18",
        "Barangay 19",
        "Barangay 20",
        "Barangay 21",
        "Barangay 22",
        "Barangay 23",
        "Barangay 24",
        "Barangay 25",
        "Barangay 26",
        "Barangay 27",
        "Barangay 28",
        "Barangay 29",
        "Barangay 30",
        "Barangay 31",
        "Barangay 32",
        "Barangay 33",
        "Barangay 34",
        "Barangay 35",
        "Barangay 36",
        "Barangay 37",
        "Barangay 38",
        "Barangay 39",
        "Barangay 40",
        "Barangay 41",
        "Barangay 42",
        "Barangay 43",
        "Barangay 44",
        "Barangay 45",
      ],
    },
    {
      cityName: "Pasig",
      barangayNames: [
        "Bagong Ilog",
        "Bagong Katipunan",
        "Bambang",
        "Buting",
        "Caniogan",
        "Dela Paz",
        "Kalawaan",
        "Kapasigan",
        "Kapitolyo",
        "Malinao",
        "Manggahan",
        "Maybunga",
        "Oranbo",
        "Palatiw",
        "Pinagbuhatan",
        "Pineda",
        "Rosario",
        "Sagad",
        "San Antonio",
        "San Joaquin",
        "San Jose",
        "San Miguel",
        "San Nicolas",
        "Santa Cruz",
        "Santa Lucia",
        "Santa Rosa",
        "Santo Tomas",
        "Santolan",
        "Sumilang",
        "Ugong",
      ],
    },
    {
      cityName: "San Juan",
      barangayNames: [
        "Addition Hills",
        "Balong-Bato",
        "Batis",
        "Corazon de Jesus",
        "Ermitaño",
        "Greenhills",
        "Isabelita",
        "Kabayanan",
        "Little Baguio",
        "Maytunas",
        "Onse",
        "Pasadena",
        "Pedro Cruz",
        "Progreso",
        "Rivera",
        "Salapan",
        "San Perfecto",
        "Santa Lucia",
        "Tibagan",
        "West Crame",
      ],
    },
    {
      cityName: "Taguig",
      barangayNames: [
        "Bagumbayan",
        "Bambang",
        "Calzada",
        "Central Bicutan",
        "Central Signal Village",
        "Fort Bonifacio",
        "Hagonoy",
        "Ibayo-Tipas",
        "Katuparan",
        "Ligid-Tipas",
        "Lower Bicutan",
        "Maharlika Village",
        "Napindan",
        "New Lower Bicutan",
        "North Daang Hari",
        "North Signal Village",
        "Palingon",
        "Sampaloc",
        "San Miguel",
        "Santa Ana",
        "South Daang Hari",
        "South Signal Village",
        "Tanyag",
        "Tuktukan",
        "Upper Bicutan",
        "Ususan",
        "Wawa",
      ],
    },
    {
      cityName: "Valenzuela",
      barangayNames: [
        "Arkong Bato",
        "Bagbaguin",
        "Balangkas",
        "Bignay",
        "Bisig",
        "Canumay",
        "Coloong",
        "Dalandanan",
        "Gen. T. de Leon",
        "Isla",
        "Karuhatan",
        "Lawang Bato",
        "Lingunan",
        "Mabolo",
        "Malanday",
        "Malanding",
        "Mapulang Lupa",
        "Marulas",
        "Maysan",
        "Palasan",
        "Parada",
        "Pariancillo Villa",
        "Pasolo",
        "Poblacion",
        "Polo",
        "Punturin",
        "Rincon",
        "Tagalag",
        "Talasan",
        "Ugong",
        "Viente Reales",
      ],
    },
  ],
};
